# Generated by Django 2.2.7 on 2019-11-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catergories', to='orders.Category')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kinds', to='orders.Kind')),
            ],
            options={
                'ordering': ['category', 'size', 'price'],
            },
        ),
        migrations.RemoveField(
            model_name='sub',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='size',
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='orders.Price'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='orders.Category'),
        ),
    ]
