# Generated by Django 2.2.7 on 2019-11-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sub',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
