# Generated by Django 2.2.7 on 2019-11-06 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191105_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_type', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='pizza_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_types', to='orders.PizzaType'),
        ),
        migrations.AlterField(
            model_name='sub',
            name='sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='orders.SubType'),
        ),
    ]
