# Generated by Django 2.2.7 on 2019-11-08 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191108_1815'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={'ordering': ['kind']},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['size']},
        ),
    ]
