# Generated by Django 2.2.7 on 2019-11-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191105_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='listed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
