# Generated by Django 2.2.7 on 2019-11-09 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191109_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
