# Generated by Django 2.2.7 on 2019-11-10 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_delete_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='no_price',
            field=models.BooleanField(default=False),
        ),
    ]
