# Generated by Django 2.2.7 on 2019-11-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191105_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='listed',
            new_name='on_the_menu',
        ),
        migrations.AlterField(
            model_name='menu',
            name='listed',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=5),
        ),
    ]
