# Generated by Django 2.2.7 on 2019-11-06 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191105_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(choices=[('Cheese', 'Cheese'), ('1 topping', '1 topping'), ('2 toppings', '2 toppings'), ('3 toppings', '3 toppings'), ('special', 'special')], max_length=64)),
                ('price', models.IntegerField()),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_pizza_sizes', to='orders.Size')),
                ('toppings', models.ManyToManyField(blank=True, related_name='reg_pizza_topings', to='orders.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(choices=[('Cheese', 'Cheese'), ('1 item', '1 item'), ('2 items', '2 items'), ('3 items', '3 items'), ('special', 'special')], max_length=64)),
                ('price', models.IntegerField()),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sic_pizza_sizes', to='orders.Size')),
                ('toppings', models.ManyToManyField(blank=True, related_name='sic_pizza_topings', to='orders.Topping')),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='on_the_menu',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='pizza_type',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='listed',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='PizzaType',
        ),
    ]
