# Generated by Django 2.2.7 on 2019-11-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20191109_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
