# Generated by Django 2.2.7 on 2019-11-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20191106_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='reg_pizza_topings', to='orders.Topping'),
        ),
    ]
