# Generated by Django 2.2.7 on 2019-11-06 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191106_0847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularpizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='sicilianpizza',
            name='toppings',
        ),
    ]
