# Generated by Django 2.2.7 on 2019-11-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191109_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='menu_priority',
            field=models.IntegerField(null=True),
        ),
    ]
