# Generated by Django 2.2.7 on 2019-11-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20191106_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sub',
            name='price',
            field=models.FloatField(),
        ),
    ]
