# Generated by Django 2.2.7 on 2019-11-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20191115_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='toppings',
        ),
        migrations.AddField(
            model_name='category',
            name='toppings',
            field=models.BooleanField(default=False),
        ),
    ]
