# Generated by Django 2.2.7 on 2019-11-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20191106_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularpizza',
            options={'ordering': ['price']},
        ),
    ]
