# Generated by Django 2.2.7 on 2019-11-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20191106_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='price',
            field=models.CharField(max_length=64),
        ),
    ]
