# Generated by Django 2.2.7 on 2019-11-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_profile_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, related_name='cart_items', to='orders.MenuItem'),
        ),
    ]
