# Generated by Django 2.2.7 on 2019-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20191106_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sicilianpizza',
            options={'ordering': ['price']},
        ),
        migrations.AlterModelOptions(
            name='sub',
            options={'ordering': ['price']},
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='price',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sub',
            name='price',
            field=models.CharField(max_length=64),
        ),
    ]
