# Generated by Django 2.2.7 on 2019-11-18 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20191116_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='orders.MenuItem'),
        ),
        migrations.AddField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='cart_topings', to='orders.Kind'),
        ),
    ]
