# Generated by Django 2.2.7 on 2019-11-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20191117_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='addable',
            field=models.BooleanField(default=False),
        ),
    ]
