# Generated by Django 2.2.7 on 2019-11-06 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_menu_menuitem_pizza'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='menuitem_ptr',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
