# Generated by Django 2.2.7 on 2019-11-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20191120_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cart',
        ),
        migrations.AddField(
            model_name='profile',
            name='carts',
            field=models.ManyToManyField(blank=True, related_name='users_carts', to='orders.Cart'),
        ),
    ]
