# Generated by Django 2.2.7 on 2019-11-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20191122_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='placed',
            field=models.BooleanField(default=True),
        ),
    ]
