# Generated by Django 2.2.7 on 2019-11-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_cart_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='placed',
            field=models.BooleanField(default=False),
        ),
    ]
