# Generated by Django 2.2.7 on 2019-11-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20191122_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCatergory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_category', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
