# Generated by Django 2.2.7 on 2019-11-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20191127_2309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_updated']},
        ),
        migrations.AddField(
            model_name='order',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
